default_registry = 'skills.sh'

[github]
topics = ['agent-skills', 'claude-code', 'claude-skills', 'awesome-skills', 'claude-plugin']
keywords = []
per_page = 10

[skillssh]
base_url = 'https://skills.sh'
limit = 10

[sources]
[sources.'anthropics/skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/anthropics/skills.git'
path = 'sources/anthropics--skills'
ref = 'main'
commit = '9d2f1ae187231d8199c64b5b762e1bdf2244733d'
updated = 2026-07-02T15:12:11.484413+07:00
installed = ['skills/frontend-design']

[sources.'ast-grep/agent-skill']
registry = 'manual'
provider = 'git'
url = 'https://github.com/ast-grep/agent-skill'
path = 'sources/ast-grep--agent-skill'
commit = '577f4d4507678f2c8cee150fae25e6ce309f70b1'
updated = 2026-05-09T23:59:02.761688+07:00
installed = ['skills/ast-grep']

[sources.'cloudai-x/threejs-skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/CloudAI-X/threejs-skills.git'
path = 'sources/cloudai-x--threejs-skills'
ref = 'main'
commit = 'b1c623076c661fc9b03dac19292e825a5d106823'
updated = 2026-06-22T20:40:33.260461+07:00
installed = ['skills/threejs-animation', 'skills/threejs-fundamentals', 'skills/threejs-geometry', 'skills/threejs-interaction', 'skills/threejs-lighting', 'skills/threejs-loaders', 'skills/threejs-materials', 'skills/threejs-postprocessing', 'skills/threejs-shaders', 'skills/threejs-textures']

[sources.'colbymchenry/frontend-audit-skill']
registry = 'github'
provider = 'git'
url = 'https://github.com/colbymchenry/frontend-audit-skill.git'
path = 'sources/colbymchenry--frontend-audit-skill'
ref = 'main'
commit = '2f35be45a1346d240592a0af81ce16d8fce95969'
updated = 2026-06-20T19:15:08.003926+07:00

[sources.'greensock/gsap-skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/greensock/gsap-skills.git'
path = 'sources/greensock--gsap-skills'
ref = 'main'
commit = 'aed9cfd3277740755f6bfc1155c7aa645403b760'
updated = 2026-06-22T20:40:01.835789+07:00
installed = ['skills/gsap-core', 'skills/gsap-frameworks', 'skills/gsap-performance', 'skills/gsap-plugins', 'skills/gsap-react', 'skills/gsap-scrolltrigger', 'skills/gsap-timeline', 'skills/gsap-utils']

[sources.'heygen-com/hyperframes']
registry = 'github'
provider = 'git'
url = 'https://github.com/heygen-com/hyperframes.git'
path = 'sources/heygen-com--hyperframes'
ref = 'main'
commit = '65b20933967bce1bc416312dcade8c36f9473e33'
updated = 2026-07-02T15:12:20.618361+07:00
installed = ['skills/embedded-captions', 'skills/faceless-explainer', 'skills/general-video', 'skills/graphic-overlays', 'skills/hyperframes', 'skills/hyperframes-animation', 'skills/hyperframes-cli', 'skills/hyperframes-core', 'skills/hyperframes-creative', 'skills/hyperframes-media', 'skills/hyperframes-registry', 'skills/motion-graphics', 'skills/pr-to-video', 'skills/product-launch-video', 'skills/remotion-to-hyperframes', 'skills/slideshow', 'skills/website-to-video']

[sources.'intellectronica/agent-skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/intellectronica/agent-skills.git'
path = 'sources/intellectronica--agent-skills'
ref = 'main'
commit = '9b0e00ad1b941165e2506545bbfddafa34cf2cb8'
updated = 2026-07-02T22:39:04.711776+07:00
installed = ['skills/ultrathink']

[sources.'nextlevelbuilder/ui-ux-pro-max-skill']
registry = 'github'
provider = 'git'
url = 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill.git'
path = 'sources/nextlevelbuilder--ui-ux-pro-max-skill'
ref = 'main'
commit = '247bf48d0245a2bfb252ac6f3b4b434bfc9a6281'
updated = 2026-07-02T22:38:52.216444+07:00
installed = ['skills/ui-ux-pro-max']

[sources.'pbakaus/impeccable']
registry = 'github'
provider = 'git'
url = 'https://github.com/pbakaus/impeccable.git'
path = 'sources/pbakaus--impeccable'
ref = 'main'
commit = '44c27a72af98394c32691ba79358811bff86bde6'
updated = 2026-07-02T14:08:03.246026+07:00
installed = ['skills/impeccable']

[sources.'remorses/playwriter@main']
registry = 'github'
provider = 'git'
url = 'https://github.com/remorses/playwriter.git'
path = 'sources/remorses--playwriter@main'
ref = 'main'
commit = 'be17216cd9ece074d661fb0887ba8b52a44b3f05'
updated = 2026-07-02T15:12:05.125923+07:00

[sources.'samhvw8/claude-code-profile']
registry = 'github'
provider = 'git'
url = 'https://github.com/samhvw8/claude-code-profile.git'
path = 'sources/samhvw8--claude-code-profile'
ref = 'main'
commit = 'a5563faa24302b788a4a3922da9df5ca3fceae7c'
updated = 2026-07-02T22:48:18.896805+07:00
installed = ['skills/ccp']

[sources.'tw93/waza']
registry = 'github'
provider = 'git'
url = 'https://github.com/tw93/Waza.git'
path = 'sources/tw93--waza'
ref = 'main'
commit = 'ac1cc9d685718996df081d70e677d527c3ff981f'
updated = 2026-07-02T22:39:04.711099+07:00
installed = ['skills/think']

[sources.'vercel-labs/agent-skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/vercel-labs/agent-skills.git'
path = 'sources/vercel-labs--agent-skills'
ref = 'main'
commit = 'f8a72b9603728bb92a217a879b7e62e43ad76c81'
updated = 2026-06-17T22:41:46.187731+07:00
installed = ['skills/react-best-practices']

[sources.'vercel-labs/next-skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/vercel-labs/next-skills.git'
path = 'sources/vercel-labs--next-skills'
ref = 'main'
commit = 'b76d687cf3e026eac3b1032f610f06b47a56377c'
updated = 2026-07-02T15:12:13.583799+07:00

[sources.'wshobson/agents']
registry = 'github'
provider = 'git'
url = 'https://github.com/wshobson/agents.git'
path = 'sources/wshobson--agents'
ref = 'main'
commit = '5cc2549a50fc672230efd0a0307e2fd27ffba792'
updated = 2026-07-02T15:12:08.072698+07:00
