default_registry = 'skills.sh'

[github]
topics = ['agent-skills', 'claude-code', 'claude-skills', 'awesome-skills', 'claude-plugin']
keywords = []
per_page = 10

[skillssh]
base_url = 'https://skills.sh'
limit = 10

[sources]
[sources.'nextlevelbuilder/ui-ux-pro-max-skill']
registry = 'github'
provider = 'git'
url = 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill.git'
path = 'sources/nextlevelbuilder--ui-ux-pro-max-skill'
ref = 'main'
commit = 'b7e3af80f6e331f6fb456667b82b12cade7c9d35'
updated = 2026-04-24T21:08:26.248057425+07:00
installed = ['skills/ui-ux-pro-max']

[sources.'remorses/playwriter@main']
registry = 'github'
provider = 'git'
url = 'https://github.com/remorses/playwriter.git'
path = 'sources/remorses--playwriter@main'
ref = 'main'
commit = 'e9918fcadc2462576dc0afb5942d77317d8b593d'
updated = 2026-04-24T21:08:28.896724236+07:00

[sources.'vercel-labs/next-skills']
registry = 'github'
provider = 'git'
url = 'https://github.com/vercel-labs/next-skills.git'
path = 'sources/vercel-labs--next-skills'
ref = 'main'
commit = '038954e07bfc313e97fa5f6ff7caf87226e4a782'
updated = 2026-04-24T21:08:30.412143156+07:00

[sources.'wshobson/agents']
registry = 'github'
provider = 'git'
url = 'https://github.com/wshobson/agents.git'
path = 'sources/wshobson--agents'
ref = 'main'
commit = '27a7ed95755a5c3a2948694343a8e2cd7a7ef6fb'
updated = 2026-04-24T21:08:32.693639802+07:00
