[settings]
experimental = true
legacy_version_file_disable_tools = ['java']

[tools]
chezmoi = "2.38.0"
devspace = "6.2.4"
direnv = "2.32.2"
dive = "0.10.0"
dotnet = "8.0.203"
duf = "0.8.1"
gallery-dl = "1.25.1"
gcloud = "434.0.0"
helm = "3.16.3"
hyperfine = "1.16.1"
jq = "1.6"
k9s = "0.32.7"
krew = "0.4.3"
kubecm = "0.21.1"
kubectl = "1.31.3"
kubectx = "0.9.4"
nodejs = "18.17.0"
peco = "0.5.10"
python = "3.9.16"
ripgrep = "12.1.1"
rust = "1.82.0"
shellcheck = "0.9.0"
shfmt = "3.3.0"
terraform = "1.7.5"
zig = "0.11.0"
go = "1.23.1"
just = "1.35.0"
flutter = "3.24.3-stable"
fluttergen = "5.7.0"
swift-package-list = "4.4.0"
swiftgen = "6.6.3"
k6 = "0.54.0"
bun = "1.1.34"
node = "22.11.0"
"cargo:https://codeberg.org/mergiraf/mergiraf" = "tag:v0.3.0"
"ubi:ast-grep/ast-grep" = "latest"
air = "1.61.1"
"ubi:F1bonacc1/process-compose" = "latest"
"asdf:martino/asdf-process-compose" = "latest"
